### ISSUE TITLE
List of feeds

### ISSUE THREAD

**Issue by 77kevink** [GetStream/react-activity-feed#112]
When i get activities from people i follow like this:

const user = client.feed('feed_one_flat', `${profileId}`, `${getstreamToken}`);
const feeds = await user.get({ limit: limit || 10 });

i get also my activities. Is there a way to get only activities from people i follow?

**Comment by tbarbugli** [comment]
you get your own activities because one of these reasons:

- you add activities to your `feed_one_flat:${profileId}` feed (either directly or via `to` target field)
- your `feed_one_flat:${profileId}` feed is following the personal feed where activities are added

**Comment by 77kevink** [comment]
Ok, but is there any way to filter feeds i get with 'get' method? For example can i pass some ore one ID to this method from which i don't want to get feeds?

**Comment by tbarbugli** [comment]
that's not supported by the API, it would not be very feasible because in most cases you would not know which feeds to filter out. Unless you need very complex filtering logic the simplest approach is to have different timelines (ie. use 1 timeline to follow N feeds and another to follow M feeds). If you can provide more info on your use case I am happy to help :)

**Comment by arnautov-anton** [comment]
Closing for now as there has not been any response from the issuer for a while. Feel free to reopen if anything changes.
