### ISSUE TITLE
Notification in notificationDropdown is not in proper time sequence.

### ISSUE THREAD

**Issue by parthsavaliya1** [GetStream/react-activity-feed#199]
https://prnt.sc/10tex6z

**Comment by mahboubii** [comment]
hey @parthsavaliya1, this could potentially be caused by the grouping logic you use for the notification feed. You can see some examples in the [Dashboard](https://getstream.io/dashboard) if you go to your Notification feed settings.

Going to close this for sake of cleanup, feel free to respond here if you still had any issues.
