### ISSUE TITLE
NotificationDropDown real-time updates

### ISSUE THREAD

**Issue by dco5** [GetStream/react-activity-feed#24]
Hello,
NotificationDropdown only seems to update real-time when dropdown is open, is this the intended usage? I was hoping to update also if dropdown is close, right now if I get a new notification, the number does not show, only if I reload the page it does show up. I can also see this message on the console log 

> _now listening to changes in realtime for messages:2806_

 when the NotificationDropdown is open 

```
<NotificationDropdown Group={group => {
            return (
                <MessageNotification activityGroup={group.activityGroup}/>
            );
          }} feedGroup="messages" notify={true}/>
```

**Comment by JelteF** [comment]
Good to hear you figured something out, but there is a much easier way to make this work. You should change the [`sharedFeeds` prop in your `StreamApp` component](https://getstream.github.io/react-activity-feed/#streamapp). By default this is set to make NotificationDropdown work for the "notification" feed group. If you change "notification" in the default value of this prop to "messages" everything should work automatically.

I just updated the docs for StreamApp and NotificationDropdown after seeing this issue, because this behaviour was not documented at all. So thanks for the bug report.

**Comment by dco5** [comment]
Works great! Thanks!
